networks:
  batch-network:
    driver: bridge
services:
  xrpl-xpop:
    container_name: xrpl-xpop
    image: wietsewind/xpop:latest
    volumes:
        - ./xrpl/store:/usr/src/app/store
    environment:
      - EVENT_SOCKET_PORT=3000
      - PUBLIC_PORT=${PORT:-3000}
      - URL_PREFIX=${URL_PREFIX:-http://localhost:${PORT:-3000}}
      - NETWORKID=0
      - UNLURL=https://vl.xrplf.org
      - UNLKEY=ED45D1840EE724BE327ABE9146503D5848EFD5F38B6D5FEDE71E80ACCE5E6E738B
      - NODES=wss://xrplcluster.com,wss://s2.ripple.com
      - FIELDSREQUIRED=Fee,Account,OperationLimit
      - NOVALIDATIONLOG=1
      - NOELIGIBLEFULLTXLOG=1
      - ONLYUNLVALIDATIONS=${ONLYUNLVALIDATIONS}
      - DEBUG=${DEBUG}
      - TELEMETRY=${TELEMETRY:-NO}
    restart: unless-stopped
    healthcheck:
        test: wget --spider -q http://localhost:3000/health || exit 1
        interval: 15s
        retries: 2
        start_period: 5s
        timeout: 5s
  xahau-xpop:
    container_name: xahau-xpop
    image: wietsewind/xpop:latest
    volumes:
        - ./xahau/store:/usr/src/app/store
    environment:
      - EVENT_SOCKET_PORT=3001
      - PUBLIC_PORT=${PORT:-3001}
      - URL_PREFIX=${URL_PREFIX:-http://localhost:${PORT:-3001}}
      - NETWORKID=21337
      - UNLURL=https://vl.xahau.org/
      - UNLKEY=EDA46E9C39B1389894E690E58914DC1029602870370A0993E5B87C4A24EAF4A8E8
      - NODES=wss://xahau.network
      - FIELDSREQUIRED=Fee,Account,OperationLimit
      - NOVALIDATIONLOG=1
      - NOELIGIBLEFULLTXLOG=1
      - ONLYUNLVALIDATIONS=${ONLYUNLVALIDATIONS}
      - DEBUG=${DEBUG}
      - TELEMETRY=${TELEMETRY:-NO}
    restart: unless-stopped
    healthcheck:
        test: wget --spider -q http://localhost:3001/health || exit 1
        interval: 15s
        retries: 2
        start_period: 5s
        timeout: 5s
  xrpl-bridge:
    container_name: xrpl-bridge
    image: xrpl:bridge
    build: .
    volumes:
        - ./xrpl/store:/usr/src/app/store
    environment:
      - FOLDER_PATH=/usr/src/app/store/xpop
      - RPC_URL=https://xahau.network
      - UNL_KEY=ED45D1840EE724BE327ABE9146503D5848EFD5F38B6D5FEDE71E80ACCE5E6E738B
      - NETWORK_ID=21337
      - BRIDGE_ACCOUNT=
      - BRIDGE_ACCOUNT_SEED=
  xahau-bridge:
    container_name: xahau-bridge
    image: xahau:bridge
    build: .
    volumes:
        - ./xahau/store:/usr/src/app/store
    environment:
      - FOLDER_PATH=/usr/src/app/store/xpop
      - RPC_URL=https://xrplcluster.com
      - UNL_KEY=EDA46E9C39B1389894E690E58914DC1029602870370A0993E5B87C4A24EAF4A8E8
      - NETWORK_ID=0
      - BRIDGE_ACCOUNT=
      - BRIDGE_ACCOUNT_SEED=

version: '3.9'
